name: Daily and Manual API Spider

on:
  schedule:
    - cron: '0 2 * * *'  # 每天台灣時間上午 10 點 (UTC+8)
  workflow_dispatch:     # 手動觸發

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas requests

    - name: Run API crawler
      run: python api.py

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: api-csv
        path: api.csv
    env:
      ACTIONS_STEP_DEBUG: true

  
