name: Daily and Manual API Spider

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Run API crawler
      run: python api.py

    - name: Commit and push result
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add api.csv
        git commit -m "Update API result [auto]"
        git push
